name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Check
      run: cargo check --verbose --all
    - name: Fmt
      run: cargo fmt --check --verbose --all
    - name: Clippy
      run: cargo clippy --verbose --all
    - name: Run tests
      run: cargo test --verbose --all

  publish_crate:
    name: Push crate to crates.io
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Publish Crate
        run: cargo publish --token ${{ secrets.CRATES_API_TOKEN }}
